"use server";

import { GoogleGenAI } from "@google/genai";

const apiKey = process.env.GEMINI_API_KEY;

export async function generateMemeImage(prompt: string) {
    if (!apiKey) {
        return { error: "GEMINI_API_KEY is not set in environment variables." };
    }

    try {
        const ai = new GoogleGenAI({ apiKey });

        const enhancementPrompt = `Create a funny visual meme based on this idea: "${prompt}". 
        Make it high quality, vivid, and suitable for a meme format.`;

        console.log("Generating image with gemini-2.5-flash-image...");

        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash-image",
            contents: enhancementPrompt,
        });

        let imageUrl = "";
        let enhancedPrompt = "";

        if (response.candidates?.[0]?.content?.parts) {
            for (const part of response.candidates[0].content.parts) {
                if (part.text) {
                    enhancedPrompt += part.text;
                } else if (part.inlineData) {
                    const imageData = part.inlineData.data;
                    // Provide a data URI so the frontend can display it immediately
                    // Assuming PNG (common for GenAI, but could be JPEG)
                    // The SDK documentation example output implies raw bytes or base64.
                    // 'imageData' from inlineData is usually a Base64 string.
                    imageUrl = `data:image/png;base64,${imageData}`;
                }
            }
        }

        if (imageUrl) {
            return {
                success: true,
                imageUrl: imageUrl,
                enhancedPrompt: enhancedPrompt || prompt
            };
        } else {
            return { error: "No image generated by the model." };
        }

    } catch (error: any) {
        console.error("Gemini Error:", error);
        return { error: error.message || "Failed to generate meme." };
    }
}

export async function generateMemeDescription(imageBase64: string) {
    if (!apiKey) {
        return { error: "GEMINI_API_KEY is not set in environment variables." };
    }

    try {
        const ai = new GoogleGenAI({ apiKey });

        // Base64 string might contain metadata "data:image/png;base64,", strip it if present
        const base64Data = imageBase64.replace(/^data:image\/\w+;base64,/, "");

        const response = await ai.models.generateContent({
            model: "gemini-2.0-flash-exp",
            contents: [
                {
                    role: "user",
                    parts: [
                        { text: "Describe this meme image in a short, funny, and engaging way suitable for an NFT description. max 2 sentences." },
                        { inlineData: { mimeType: "image/png", data: base64Data } }
                    ]
                }
            ]
        });

        const description = response.candidates?.[0]?.content?.parts?.[0]?.text || "No description generated.";
        return { success: true, description };

    } catch (error: any) {
        console.error("Gemini Description Error:", error);
        return { error: error.message || "Failed to generate description." };
    }
}
